/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/types.d.ts` (hash: 28a101045d505228cf0225270189532a)
interface __BaseEnv_Env {
	LEADERBOARD_DB: D1Database;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		LEADERBOARD_DB: D1Database;
	}
	interface ProductionEnv {
		LEADERBOARD_DB: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
